/****************************************************************************************
 * File:
 * ConfidenceResult.ts
 *
 * Path:
 * src/indicators/AJIndicator/engines/Confidence/ConfidenceResult.ts
 *
 * Purpose:
 * Canonical output contract for the AJ v2 Institutional Confidence Engine.
 *
 * Responsibilities:
 * -----------------
 * • Represents the complete confidence assessment for a trade.
 * • Carries weighted evidence generated by all upstream engines.
 * • Supplies confidence information to the Authority Engine.
 *
 * This file contains contracts only.
 * No calculations belong here.
 *
 * AJ Architecture
 *
 * Trend
 * Momentum
 * Market Structure
 * Liquidity
 * Order Flow
 * Volatility
 * Multi-Timeframe
 * Risk Qualification
 *          │
 *          ▼
 *     Confidence Engine
 *          │
 *          ▼
 *     Authority Decision
 ****************************************************************************************/

import type { ConfidenceEvidence } from "./ConfidenceEvidence";

//======================================================
// CONFIDENCE RESULT
//======================================================

export interface ConfidenceResult {

	//--------------------------------------------------
	// CANONICAL AI OUTPUT
	//--------------------------------------------------
	
	aiConfidence: number;
	confidenceGrade:
	
		| "A+"
		| "A"
		| "B"
		| "C"
		| "D"
		| "F";
	
	recommendation:
	
		| "STRONG_LONG"
		| "LONG"
		| "WAIT"
		| "SHORT"
		| "STRONG_SHORT"
		| "TRADE"
		| "NO_TRADE";
	
	//--------------------------------------------------
	// TEMPORARY COMPATIBILITY
	//
	// These members exist only to support
	// repository-wide migration.
	//
	// Canonical AJ v2 consumers should use:
	//
	// • aiConfidence
	// • confidenceGrade
	// • recommendation
	//
	// These compatibility members will be
	// removed only after every downstream
	// consumer has migrated.
	//
	// ConfidenceEngine remains the sole owner
	// of all confidence computation.
	//--------------------------------------------------
	
	confidence:number;
	
	tradeGrade:
	
		| "A+"
		| "A"
		| "B"
		| "C"
		| "D"
		| "F";
	
	confidenceClass:
	
		| "EXTREME"
		| "VERY_HIGH"
		| "HIGH"
		| "MEDIUM"
		| "LOW"
		| "VERY_LOW"
		| "NONE";

    //--------------------------------------------------
    // FACTORS
    //--------------------------------------------------

    positiveFactors: string[];
    negativeFactors: string[];

    //--------------------------------------------------
    // EVIDENCE
    //--------------------------------------------------

    evidence:ConfidenceEvidence[];
    evidenceWeight: number;

    evidenceSummary:{
        totalEvidence: number;
        positiveEvidence: number;
        negativeEvidence: number;
    };

    //--------------------------------------------------
    // TOP FACTORS
    //--------------------------------------------------

    strongestPositive?: ConfidenceEvidence;
    strongestNegative?: ConfidenceEvidence;

    //--------------------------------------------------
    // FLAGS
    //--------------------------------------------------

    tradeQualified: boolean;
    institutionalGrade: boolean;

	//--------------------------------------------------
	// DIAGNOSTICS
	//
	// Produced only by ConfidenceEngine.
	//
	// Consumers may read these values for:
	//
	// • debugging
	// • dashboards
	// • telemetry
	//
	// Consumers must never recalculate them.
	//--------------------------------------------------

	diagnostics: {
		aiConfidence: number;
		confidence?: number;
		normalizedScore: number;
		rawScore: number;
		maximumScore: number;
		recommendation?: string;
		confidenceGrade?: string;
        evidenceCount?: number;
        positiveCount?: number;
        negativeCount?: number;
        positiveWeight?: number;
        negativeWeight?: number;
    };

}